### ISSUE TITLE
Issues deploying.

### ISSUE THREAD

**Issue by malandriso** [JitendraZaa/LightningLookup#1]
Hello, I get the following errors when deploying the component:

**Lookup.cmp**

```
FIELD_INTEGRITY_EXCEPTION

Failed to save Lookup.cmp: Invalid definition for null:Lookup: null: Source
```
and

**Lookup.design**

```
FIELD_INTEGRITY_EXCEPTION

Failed to save Lookup.design: The design file contains attribute 'objectName' but the component doesn't.: Source
```

**Comment by JitendraZaa** [comment]
I missed to commit dependent Apex Class. Please try again. Should work now.

**Comment by KritikaKelawat** [comment]
Lookup.cmp

FIELD_INTEGRITY_EXCEPTION
Failed to save Lookup.cmp: Invalid definition for null:Lookup: ApexService.getType() return null with currentNamespace: null, namespace: null, name: Lookup: Source
